language: node_js

node_js:
  - 12

cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache

script:
  - yarn build

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - yarn build
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
